# Week of 2023-04-17 to 2023-04-24 (26)

### Got @pytorchbot revert command, but no corresponding commit (25)

- cannot find commit corresponding to @pytorchbot revert comment
  - Revert to reland this as this miss one change in mac build workflow. My mistake from rebasing from master into main ([comment](https://github.com/pytorch/pytorch/pull/99121#issuecomment-1512264581))
- cannot find commit corresponding to @pytorchbot revert comment
  - No longer needed ([comment](https://github.com/pytorch/pytorch/pull/99579#issuecomment-1515820722))
- cannot find commit corresponding to @pytorchbot revert comment
  - Found a clue on the uploaded archive, reverting this so I can update the PR with the correct mitigation ([comment](https://github.com/pytorch/pytorch/pull/99506#issuecomment-1518252418))
- cannot find commit corresponding to @pytorchbot revert comment
  - breaks inductor ([comment](https://github.com/pytorch/pytorch/pull/99447#issuecomment-1514013091))
- cannot find commit corresponding to @pytorchbot revert comment
  - Reverting the previous PR ([comment](https://github.com/pytorch/pytorch/pull/99581#issuecomment-1515817141))
- cannot find commit corresponding to @pytorchbot revert comment
  - Regressed behavior ([comment](https://github.com/pytorch/pytorch/pull/99526#issuecomment-1516313920))
- cannot find commit corresponding to @pytorchbot revert comment
  - Sorry for reverting your PR but a bunch of inductor tests are failing after this commit, so reverting the PR just to be sure ([comment](https://github.com/pytorch/pytorch/pull/98706#issuecomment-1518444021))
- cannot find commit corresponding to @pytorchbot revert comment
  - Apparently this is breaking inductor on master? So weird ([comment](https://github.com/pytorch/pytorch/pull/99279#issuecomment-1511967868))
- cannot find commit corresponding to @pytorchbot revert comment
  - Sorry for reverting your PR, but it breaks MacOS test in trunk ([comment](https://github.com/pytorch/pytorch/pull/97203#issuecomment-1514047636))
- cannot find commit corresponding to @pytorchbot revert comment
  - reverting this one too for safety ([comment](https://github.com/pytorch/pytorch/pull/99276#issuecomment-1511972021))
- cannot find commit corresponding to @pytorchbot revert comment
  - malfet already directly fixed it ([comment](https://github.com/pytorch/pytorch/pull/99370#issuecomment-1513128507))
- cannot find commit corresponding to @pytorchbot revert comment
  - dynamo/test_after_aot.py::TestAfterAot::test_save_graph_repro - AssertionError, see https://github.com/pytorch/pytorch/actions/runs/4750274195/jobs/8438535867 ([comment](https://github.com/pytorch/pytorch/pull/99478#issuecomment-1515790998))
- cannot find commit corresponding to @pytorchbot revert comment
  - CI Fail ([comment](https://github.com/pytorch/pytorch/pull/99362#issuecomment-1513973050))
- cannot find commit corresponding to @pytorchbot revert comment
  - Diagnosing if sebotnet has flakiness ([comment](https://github.com/pytorch/pytorch/pull/98988#issuecomment-1515099552))
- cannot find commit corresponding to @pytorchbot revert comment
  - Broke inductor, see https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=inductor%2C%201%2C%201 ([comment](https://github.com/pytorch/pytorch/pull/98483#issuecomment-1513654507))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/98965#issuecomment-1514561840))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99170#issuecomment-1512922761))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99539#issuecomment-1517484303))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/98590#issuecomment-1517555266))
- cannot find commit corresponding to @pytorchbot revert comment
  - Diff reverted internally ([comment](https://github.com/pytorch/pytorch/pull/99492#issuecomment-1515360979))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/98440#issuecomment-1513090063))
- cannot find commit corresponding to @pytorchbot revert comment
  - back out diff that doubles memory consumption for multitask FAIM flows. See D44978317 ([comment](https://github.com/pytorch/pytorch/pull/97824#issuecomment-1512048303))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/98793#issuecomment-1517526663))
- cannot find commit corresponding to @pytorchbot revert comment
  - Break internal build ([comment](https://github.com/pytorch/pytorch/pull/99320#issuecomment-1516044479))
- cannot find commit corresponding to @pytorchbot revert comment
  - Diff reverted internally ([comment](https://github.com/pytorch/pytorch/pull/99220#issuecomment-1518166594))

### GHFirst (1)

- [Revert "[quant][fix] Compare resnet with quantizer api with the prepare_fx and decomposed convert flow (#98905)"](https://github.com/pytorch/pytorch/commit/20a1788136166ace127c12d1e8f38779be1a5e34)
  - Conflicts with D44918496 landed internally, blocks diff train import ([comment](https://github.com/pytorch/pytorch/pull/98905#issuecomment-1510533477))
